version: "2.1"

services:
  database:
    image: neo4j:3.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    healthcheck:
      test: curl -i http://127.0.0.1:7474 2>&1 | grep -c -e '200 OK'
      interval: 5s
      timeout: 30s
      retries: 3
