version: "2.1"

services:
  wait:
    image: alpine
    depends_on:
      app:
        condition: service_healthy
  app:
    image: ${APP_NAME}
    build:
      context: ..
      dockerfile: ./containers/Dockerfile
      args:
        - BUILDER_IMAGE=${BUILDER_IMAGE_NAME}
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://localhost:3000/health || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 6
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 3
