name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Go 1.X
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Unit tests
        run: go test -v .

      - name: Build image
        run: docker build -f containers/Dockerfile -t crounch .

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags
        run: |
          docker tag crounch ${{ secrets.DOCKER_USER }}/crounch-back:$(echo ${GITHUB_SHA} | cut -c1-7)
          docker tag crounch ${{ secrets.DOCKER_USER }}/crounch-back:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/crounch-back:$(echo ${GITHUB_SHA} | cut -c1-7)
          docker push ${{ secrets.DOCKER_USER }}/crounch-back:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: "./deploy.sh"
