name: Slow tests

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  slow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Go 1.X
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Acceptance tests
        run: make acceptance-test
